---
#--------------------------------------------------------------#
# Create Directory
#--------------------------------------------------------------#
# assumption:
#   {{ pg_fs_main }} for main data   , default: `/data`              [fast ssd]
#   {{ pg_fs_bkup }} for backup data , default: `/data/backups`     [cheap hdd]
#--------------------------------------------------------------#
# default variable:
#     pg_fs_main = /data             fast ssd
#     pg_fs_bkup = /data/backups     cheap hdd (optional)
#
#     /pg      -> /data/postgres/pg-test-17    (soft link)
#     /pg/data -> /data/postgres/pg-test-17/data
#--------------------------------------------------------------#
- name: create pgsql directories
  tags: pg_dir
  become: yes
  block:

    # pg_cluster_dir:    "{{ pg_fs_main }}/postgres/{{ pg_cluster }}-{{ pg_version }}"
    - name: create pgsql directories
      file: path={{ item.path }} state=directory owner={{ item.owner|default(pg_dbsu) }} group={{ item.group|default('postgres') }} mode={{ item.mode }}
      with_items:
        - { path: "{{ pg_fs_main }}"            ,mode: "0777" , owner: "root" , group: "root" }
        - { path: "{{ pg_fs_bkup }}"            ,mode: "0777" , owner: "root" , group: "root" }
        - { path: "{{ pg_fs_main }}/postgres"   ,mode: "0700" }
        - { path: "{{ pg_cluster_dir }}"        ,mode: "0700" }
        - { path: "{{ pg_cluster_dir }}/bin"    ,mode: "0700" }
        - { path: "{{ pg_cluster_dir }}/tmp"    ,mode: "0700" }
        - { path: "{{ pg_cluster_dir }}/cert"   ,mode: "0700" }
        - { path: "{{ pg_cluster_dir }}/conf"   ,mode: "0700" }
        - { path: "{{ pg_cluster_dir }}/data"   ,mode: "0700" }
        - { path: "{{ pg_cluster_dir }}/meta"   ,mode: "0700" }
        - { path: "{{ pg_cluster_dir }}/stat"   ,mode: "0700" }
        - { path: "{{ pg_cluster_dir }}/spool"  ,mode: "0700" }
        - { path: "{{ pg_cluster_dir }}/change" ,mode: "0700" }
        - { path: "{{ pg_backup_dir }}/backup"  ,mode: "0700" }
        - { path: "/var/run/postgresql"         ,mode: "0755" }   # pid dir
        - { path: "{{ pg_cluster_dir }}/log"    ,mode: "0750" }   # log dir
        - { path: "{{ patroni_log_dir }}"       ,mode: "0750" }
        - { path: "{{ pgbouncer_log_dir }}"     ,mode: "0750" }
        - { path: "{{ pgbackrest_log_dir }}"    ,mode: "0750" }
        - { path: "/etc/patroni"                ,mode: "0700" }   # conf dir
        - { path: "/etc/pgbackrest"             ,mode: "0700" }
        - { path: "/etc/pgbouncer"              ,mode: "0700" }
        - { path: "/etc/pg_exporter"            ,mode: "0700" }

    # do not create log dir inside data dir (create when data dir is not prefix of log dir)
    - name: create external postgres log dir
      when: not ( pg_log_dir.startswith(pg_data) )
      file: path={{ pg_log_dir }} state=directory owner={{ pg_dbsu }} group=postgres mode=0700

    # make sure the /var/run/postgresql is created
    - name: create tmpfiles.d for /var/run/postgresql
      copy:
        dest: /etc/tmpfiles.d/postgresql.conf
        content: "d /var/run/postgresql 0755 {{ pg_dbsu }} postgres -"
        owner: root
        group: root
        mode: '0644'

    # create /pg soft link
    - name: link pgsql directories
      file: src={{ item.src }} dest={{ item.dest }} state=link
      with_items:
        - { src: "{{ pg_backup_dir }}/backup" ,dest: "{{ pg_cluster_dir }}/backup" }
        - { src: "{{ pg_cluster_dir }}"       ,dest: "/pg" }

    # reserve dummy file for disk-full emergency
    - name: create dummy file
      tags: pg_dummy
      command: fallocate -l {{ pg_dummy_filesize|default('64MiB') }} /pg/dummy
...