---
#--------------------------------------------------------------#
# PostgreSQL Bash Scripts                               [pg_bin]
#--------------------------------------------------------------#
# sync files/postgres -> /pg/bin/
- name: copy /pg/bin/ scripts
  tags: pg_bin
  copy: src=postgres/ dest=/pg/bin/ owner={{ pg_dbsu }} group=postgres mode=0755


#--------------------------------------------------------------#
# PostgreSQL Alias & Shortcuts and PSQL Client Config [pg_alias][pg_psql]
#--------------------------------------------------------------#
- name: copy postgres alias and psqlrc files
  tags: pg_alias
  template: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { src: "pg-alias" ,dest: "/etc/profile.d/pg-alias.sh" ,owner: "root"          ,group: "root"     ,mode: "0644" }
    - { src: "psqlrc"   ,dest: "{{ pg_dbsu_home }}/.psqlrc" ,owner: "{{ pg_dbsu }}" ,group: "postgres" ,mode: "0600" }

...