---
#--------------------------------------------------------------#
# Resume Patroni HA                                     [resume]
#--------------------------------------------------------------#
- name: resume patroni ha
  become_user: "{{ pg_dbsu }}"
  tags: [ up, resume ]
  ignore_errors: true
  shell: |
    {% if pg_mode|default('pgsql') == 'citus' %} 
    OUTPUT=$(/usr/bin/patronictl -c /etc/patroni/patroni.yml resume {{ pg_shard }} --group {{ pg_group }} 2>&1)
    RET=$?
    {% else %}
    OUTPUT=$(/usr/bin/patronictl -c /etc/patroni/patroni.yml resume {{ pg_cluster }} 2>&1)
    RET=$?
    {% endif %}
    if [ $RET -eq 0 ]; then
        echo "Patroni resume successfully."
        exit 0
    else
        if echo "$OUTPUT" | grep -qi 'is not paused'; then
            echo "Patroni already resumed"
            exit 0
        else
            echo "Failed to resume patroni $RET, please check the logs."
            echo "$OUTPUT"
            exit 1
        fi
    fi

...